root: true
parser: '@typescript-eslint/parser'
plugins:
  - '@typescript-eslint'
extends:
  - '@janejeon'
  - plugin:@typescript-eslint/recommended
  - plugin:import/recommended
  - plugin:import/typescript
# settings:
#   import/parsers:
#     '@typescript-eslint/parser': ['.ts', '.tsx']
